#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(new URL("..", import.meta.url).pathname);
const publicationsPath = path.join(root, "assets/data/publications/publications.json");
const constructionStepsPath = path.join(root, "_data/construction_spine/construction-spine-100.json");
const workerPath = path.join(root, "workers/prrp-short-routes.js");
const testPath = path.join(root, "test/prrp-short-routes.test.mjs");

const FRIENDLY_ALIASES = [
  ["/wp-glance", "https://panta-rhei.site/publications/anchor-documents/wp000-panta-rhei-at-a-glance/"],
  ["/wp-theory", "https://panta-rhei.site/publications/anchor-documents/wp002-t-theory-executive-synopsis/"],
  ["/wp-taulib", "https://panta-rhei.site/publications/anchor-documents/wp003-taulib-technical-overview/"],
  ["/wp-observatory", "https://panta-rhei.site/publications/anchor-documents/wp004-public-research-observatory-blueprint/"],
  ["/wp-impact", "https://panta-rhei.site/publications/anchor-documents/wp005-global-public-good-impact-overview/"],
  ["/anchor-documents", "https://panta-rhei.site/publications/anchor-documents/"]
];

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function routePath(shortUrl) {
  const url = new URL(shortUrl);
  const pathname = url.pathname === "/" ? "/" : url.pathname.replace(/\/+$/, "");
  return pathname.toLowerCase();
}

function addRoute(routes, source, target) {
  if (!source || !target) return;
  const key = source.startsWith("http") ? routePath(source) : source.toLowerCase();
  if (!key.startsWith("/")) {
    throw new Error(`Short route must start with /: ${key}`);
  }
  const targetUrl = new URL(target, "https://panta-rhei.site").toString();
  const existing = routes.get(key);
  if (existing && existing !== targetUrl) {
    throw new Error(`Conflicting target for ${key}: ${existing} vs ${targetUrl}`);
  }
  routes.set(key, targetUrl);
}

function publicationRecords() {
  const payload = readJson(publicationsPath);
  return Array.isArray(payload) ? payload : payload.publications;
}

function constructionStepRecords() {
  const payload = readJson(constructionStepsPath);
  return Array.isArray(payload) ? payload : payload.steps || payload.construction_steps || [];
}

const routes = new Map();
addRoute(routes, "/", "https://panta-rhei.site/");

for (const record of publicationRecords()) {
  if (!record.short_url || !record.canonical_url) continue;
  if (record.status !== "released") continue;
  addRoute(routes, record.short_url, record.canonical_url);
}

for (const [source, target] of FRIENDLY_ALIASES) {
  addRoute(routes, source, target);
}

for (const step of constructionStepRecords()) {
  const canonical = step.canonical_route || step.canonical_url || step.canonical_path || step.route;
  const primary = step.short_route || step.short_url;
  const padded = step.padded_short_route || step.short_route_padded || step.short_url_padded;
  addRoute(routes, primary, canonical);
  addRoute(routes, padded, canonical);
}

const routeEntries = [...routes.entries()].sort(([left], [right]) => {
  if (left === "/") return -1;
  if (right === "/") return 1;
  return left.localeCompare(right, "en");
});

function jsString(value) {
  return JSON.stringify(value);
}

const workerSource = `// Generated by scripts/generate_prrp_short_routes.mjs. Do not edit route entries by hand.\n` +
`export const ROUTE_ENTRIES = [\n` +
routeEntries.map(([source, target]) => `  [${jsString(source)}, ${jsString(target)}]`).join(",\n") +
`\n];\n\n` +
`const ROUTES = new Map(ROUTE_ENTRIES);\n\n` +
`function normalizedPath(pathname) {\n` +
`  if (pathname === "/") return "/";\n` +
`  return pathname.replace(/\\/+$/, "").toLowerCase();\n` +
`}\n\n` +
`export function shortRouteTarget(requestUrl) {\n` +
`  const url = new URL(requestUrl);\n` +
`  const target = ROUTES.get(normalizedPath(url.pathname));\n` +
`  if (!target) return null;\n\n` +
`  const targetUrl = new URL(target);\n` +
`  targetUrl.search = url.search;\n` +
`  return targetUrl.toString();\n` +
`}\n\n` +
`export default {\n` +
`  async fetch(request) {\n` +
`    const target = shortRouteTarget(request.url);\n` +
`    if (target) {\n` +
`      return Response.redirect(target, 301);\n` +
`    }\n\n` +
`    return new Response("Unknown Panta Rhei short route.", {\n` +
`      status: 404,\n` +
`      headers: {\n` +
`        "Content-Type": "text/plain; charset=utf-8",\n` +
`        "Cache-Control": "public, max-age=300"\n` +
`      }\n` +
`    });\n` +
`  }\n` +
`};\n`;

const testSource = `import assert from "node:assert/strict";\n` +
`import worker, { ROUTE_ENTRIES, shortRouteTarget } from "../workers/prrp-short-routes.js";\n\n` +
`const expectedRoutes = new Map(ROUTE_ENTRIES);\n\n` +
`assert.equal(expectedRoutes.size, ROUTE_ENTRIES.length, "short routes must be unique");\n` +
`assert(expectedRoutes.size >= 280, "route table should include publication and 100-step routes");\n\n` +
`for (const [source, target] of expectedRoutes) {\n` +
`  assert.equal(shortRouteTarget(\`https://prrp.site\${source}\`), target);\n` +
`  if (source !== "/") {\n` +
`    assert.equal(shortRouteTarget(\`https://prrp.site\${source}/\`), target);\n` +
`  }\n` +
`}\n\n` +
`const samples = new Map([\n` +
`  ["https://prrp.site/", "https://panta-rhei.site/"],\n` +
`  ["https://prrp.site/wp000", "https://panta-rhei.site/publications/anchor-documents/wp000-panta-rhei-at-a-glance/"],\n` +
`  ["https://prrp.site/rn007", "https://panta-rhei.site/publications/research-notes/aesthetic-topology-pre-symbolic-readout/"],\n` +
`  ["https://prrp.site/rp005", "https://panta-rhei.site/publications/research-papers/tau-holomorphy-boundary-algebra/"],\n` +
`  ["https://prrp.site/pgd044", "https://panta-rhei.site/publications/research-briefings/public-good/wildfire-smoke-heat-compound-extreme-health-protection/"],\n` +
`  ["https://prrp.site/s1", "https://panta-rhei.site/corpus/construction-spine/steps/001-non-import-discipline/"],\n` +
`  ["https://prrp.site/s001", "https://panta-rhei.site/corpus/construction-spine/steps/001-non-import-discipline/"],\n` +
`  ["https://prrp.site/s64", "https://panta-rhei.site/corpus/construction-spine/steps/064-tau-einstein-identity/"],\n` +
`  ["https://prrp.site/s100", "https://panta-rhei.site/corpus/construction-spine/steps/100-logos-boundary-and-ontic-closure-burden/"]\n` +
`]);\n\n` +
`for (const [source, target] of samples) {\n` +
`  assert.equal(shortRouteTarget(source), target);\n` +
`}\n\n` +
`assert.equal(\n` +
`  shortRouteTarget("https://prrp.site/wp000?utm_source=test"),\n` +
`  "https://panta-rhei.site/publications/anchor-documents/wp000-panta-rhei-at-a-glance/?utm_source=test"\n` +
`);\n` +
`assert.equal(shortRouteTarget("https://prrp.site/not-a-route"), null);\n\n` +
`const response = await worker.fetch(new Request("https://prrp.site/rn007"));\n` +
`assert.equal(response.status, 301);\n` +
`assert.equal(\n` +
`  response.headers.get("Location"),\n` +
`  "https://panta-rhei.site/publications/research-notes/aesthetic-topology-pre-symbolic-readout/"\n` +
`);\n\n` +
`const missing = await worker.fetch(new Request("https://prrp.site/not-a-route"));\n` +
`assert.equal(missing.status, 404);\n`;

fs.writeFileSync(workerPath, workerSource, "utf8");
fs.writeFileSync(testPath, testSource, "utf8");
console.log(`Generated ${routeEntries.length} prrp.site route(s).`);
